export const lightTheme = {
  accentColor: '#217346',
  accentFg: '#FFFFFF',
  accentLight: '#E5F3EC',
  textDark: '#2A2A2A',
  textMedium: '#5E5E5E',
  textLight: '#9B9B9B',
  textBubble: '#FFFFFF',
  bgIconHeader: '#737373',
  fgIconHeader: '#FFFFFF',
  textHeader: '#2A2A2A',
  textHeaderSelected: '#FFFFFF',
  bgCell: '#FFFFFF',
  bgCellMedium: '#F8F8F8',
  bgHeader: '#F5F5F5',
  bgHeaderHasFocus: '#E0E0E0',
  bgHeaderHovered: '#E8E8E8',
  bgBubble: '#217346',
  bgBubbleSelected: '#1A5C38',
  bgSearchResult: '#FFF9C4',
  borderColor: '#E0E0E0',
  drilldownBorder: '#217346',
  linkColor: '#217346',
  cellHorizontalPadding: 8,
  cellVerticalPadding: 3,
  headerFontStyle: '600 13px',
  baseFontStyle: '13px',
  fontFamily: 'Inter, sans-serif',
  editorFontSize: '13px',
  lineHeight: 1.4,
};

// Define your dark theme
export const darkTheme = {
  accentColor: '#4CAF50',
  accentFg: '#FFFFFF',
  accentLight: '#2E7D32',
  textDark: '#E0E0E0',
  textMedium: '#A0A0A0',
  textLight: '#707070',
  textBubble: '#FFFFFF',
  bgIconHeader: '#A0A0A0',
  fgIconHeader: '#FFFFFF',
  textHeader: '#E0E0E0',
  textHeaderSelected: '#FFFFFF',
  bgCell: '#121212',
  bgCellMedium: '#1E1E1E',
  bgHeader: '#1E1E1E',
  bgHeaderHasFocus: '#2E2E2E',
  bgHeaderHovered: '#252525',
  bgBubble: '#4CAF50',
  bgBubbleSelected: '#3D8B40',
  bgSearchResult: '#5D4037',
  borderColor: '#333333',
  drilldownBorder: '#4CAF50',
  linkColor: '#4CAF50',
  cellHorizontalPadding: 8,
  cellVerticalPadding: 3,
  headerFontStyle: '600 13px',
  baseFontStyle: '13px',
  fontFamily: 'Inter, sans-serif',
  editorFontSize: '13px',
  lineHeight: 1.4,
};
